### ISSUE TITLE
Graphics API Capture Problem

### ISSUE THREAD

**Issue by DevinStoen** [UW-NVIDIA-CAPSTONE/NVIDIA_Client#1]
Currently the "Capture" method in the "MainWindow.xaml.cs" class is having trouble capturing games running in Directx 8.

**Comment by rogerallen** [comment]
Hi Devin, 

Can you break down the failure a little bit more?  I'll need more info to dig into this.

* Where is the failure happening exactly?  Which call is failing?  What happened vs. what did you want to happen?  The path works for INSIDE, so that would be useful as a comparison.

Note that you can use links like this https://github.com/UW-NVIDIA-CAPSTONE/NVIDIA_Client/blob/master/WpfApplication1/MainWindow.xaml.cs#L155 just by clicking in the code on github.

**Comment by rogerallen** [comment]
Adding some info from the slack conversation:

You're getting valid info for the GetWindowDC, etc., but the BitBlt call fails with all black screen.  Googling seems to indicate this is a common issue.  

One workaround is to use GeForce Experience to do the screen capture.  Alt-F1 should snapshot the current screen.  It saves it to ~/Videos/<appname>/  & your app could look for files that appear here and use them.

I also received a pointer to what looks like an API we can use.  Please check out the Windows IDXGIOutputDuplication API to capture the screen.  https://msdn.microsoft.com/en-us/library/windows/desktop/hh404611(v=vs.85).aspx says:

IDXGIOutputDuplication is supported in Desktop Window Manager (DWM) on non-8bpp DirectX full-screen modes and non-8bpp OpenGL full-screen modes.
